### ISSUE TITLE
replace spesific pattern on post_name

### ISSUE THREAD

**Issue by juraganfilmmovie** [CodeAtCode/wp-cli-getbyurl#1]
hello , how to use wp-cli-getbyurl to replace spesific pattern for wordpress slug,
for example i have post with this slug how-to-use-wpcli-online-for-beginner , the goal is to remove -for-beginner from the slug in all post.

thank you before for your help.

**Comment by Mte90** [comment]
Hi, this is not for replacing slugs.
This is to find an id of a post by the slug, you are looking for a complete different tool.
You can do this with search&replace of wp-cli and a regex.
